server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka        

spring:
  profiles:
    active: dev
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
#          filters:
#            - AuthFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
#          filters:
#            - AuthFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
#          filters:
#            - AuthFilter
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/auth/**

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"       